### ISSUE TITLE
address gitguardian security issues

### ISSUE THREAD

**Issue by zeyus** [NLP4ALL/nlp4all#8]
this requires 
1 - removing the exposed secrets
2 - removing them from the history and any branches which they appear (slightly complicated)
3 - doing the same in the upstream repo https://github.com/arthurhjorth/nlp4all (which hopefully will be defunct at some point once github detaches the fork)

**Comment by zeyus** [comment]
It's all done on this repo, but I don't have permissions to do it on the original repo.

**Comment by zeyus** [comment]
@arthurhjorth this may be something you want to do. I have a list of the secrets that were in the repo and I used the "BFG" tool as outlined here: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

**Comment by arthurhjorth** [comment]
Oh man, I could have sworn that I kept my secrets uncommitted and out of the repo. I guess I made a lazy `git add all` at some point and included them. Thanks for the heads up!
